// Static metadata that supplements the JSON: one-liner descriptions,
// brushwork notes, and approximate dimensions for each painting in the library.

export const PAINTING_DESCRIPTIONS: Record<string, string> = {
  "met-436529":              "Monet and Renoir sat side by side at this floating café near Paris in 1869, inventing Impressionism's signature loose, sun-dappled touch.",
  "met-437980":              "One of Monet's monumental late 'Water Lilies,' painted nearly blind, dissolving the boundary between water, sky, and reflected light.",
  "met-436922":              "Monet's boldly modern terrace scene at Sainte-Adresse—flat planes and dazzling coastal sun borrowed straight from Japanese woodblock prints.",
  "met-437984":              "Painted from the Saint-Rémy asylum grounds, the swirling cypresses translate Van Gogh's emotional intensity directly into color and rhythm.",
  "met-436528":              "One of Van Gogh's last paintings at Saint-Rémy, the irises pulse with energy yet feel unusually serene compared to his turbulent final months.",
  "met-436532":              "One of thirty self-portraits Van Gogh made in Paris, each an experiment—here he tests Pointillism and a palette that would define his mature style.",
  "met-436535":              "Painted in Arles with deliberate symbolism: Van Gogh saw the oleander as a plant of life, paired with Zola's novel on joy and sorrow.",
  "met-436928":              "Degas showed ballet as grueling labor—tired dancers wait, the ballet master watches—not the polished spectacle audiences paid to see.",
  "met-437654":              "Renoir's atmospheric portrait of an unknown woman on the Normandy coast, her identity still disputed by art historians a century later.",
  "met-436005":              "This Salon triumph made Renoir fashionable overnight; Marguerite Charpentier's literary salon was the social engine of Paris in the 1870s.",
  "met-437394":              "Rembrandt imagined Aristotle contemplating Homer's bust, his hand resting on a chain given by his patron Alexander the Great—a meditation on fame and thought.",
  "met-29150":               "El Greco's only surviving pure landscape crackles with a supernatural storm that never visits real Toledo—pure spiritual theater above the city.",
  "met-435882":              "Cézanne's obsessive still lifes broke perspective open with multiple viewpoints and tilted planes, handing Picasso the key to Cubism.",
  "met-437539":              "Lautrec documented Paris nightlife as both insider and outsider, his lithographic style compressing figures into bold outlines that shaped modern graphic design.",
  "met-421165":              "Gauguin's first Tahitian masterpiece reimagines the Virgin and Child as Polynesian islanders—faith, colonialism, and longing in a single canvas.",
  "met-61333":               "The most intimate of Cézanne's five 'Card Players' versions, distilling rural Provençal farmers into monumental, almost sculptural forms.",
  "met-45434":               "Published by Hokusai around age 70, the great wave dwarfs Mount Fuji deliberately—the sea, not the mountain, is sovereign.",
  "met-0-vermeer-water-pitcher": "Vermeer's quiet interior captures northern light as liquid; the subject's identity and the action's meaning are both left deliberately open.",
  "met-0-vermeer-lute":      "Vermeer's woman pauses mid-tune, gazing toward window light—a frozen moment of private music that feels more like a memory than a painting.",
  "met-0-vermeer-asleep":    "Vermeer's first genre scene: a maid slumped over a table—ambiguous between sleep, grief, and intoxication—painted with radiant Dutch light.",
  "met-0-sargent-madame-x":  "Sargent's portrait of Madame Gautreau scandalized Paris in 1884; her pale skin and bold posture were read as flagrantly sexual.",
  "met-0-velazquez-pareja":  "Velázquez painted his enslaved assistant Juan de Pareja with such psychological presence that the portrait was exhibited before the artist's own work.",
  "met-0-homer-gulf-stream":  "Homer's Black sailor adrift on a dismasted boat surrounded by sharks drew no sympathy when exhibited—its politics were ahead of its time.",
  "met-0-homer-snap-whip":   "Homer captured the kinetic joy of a boys' game in the Catskills, turning an everyday moment into a hymn to post-Civil War American childhood.",
  "met-0-leutze-washington":  "Leutze painted this heroic crossing in Düsseldorf, his ice-choked Delaware populated by German models—American myth made in Germany.",
  "met-0-cassatt-sewing":    "Cassatt centers the unglamorous intimacy of motherhood: a woman sews while a child leans against her, ignoring the viewer completely.",
  "met-0-fragonard-reading":  "Fragonard's girl is entirely absorbed in her book—a radical act of interiority in an era when women's minds were rarely taken seriously by painters.",
  "met-0-monet-haystacks":   "Haystacks in changing light became Monet's first series—the subject is almost irrelevant; it is time itself being painted.",
  "met-0-van-gogh-olive":    "Van Gogh's olive trees twist with the same restless energy as his cypresses—nature as felt, not merely seen.",
  "met-0-hiroshige-sudden-shower": "Hiroshige's rain lines are almost calligraphic; this print so impressed Van Gogh that he painted two oil copies of it.",
  "met-0-hiroshige-plum":    "A close-cropped plum branch in crimson—Hiroshige's bold framing directly inspired Degas and the Impressionists' asymmetric compositions.",
  "met-0-bierstadt-rocky":   "Bierstadt's theatrical light turns the Rockies into a sublime stage set, performing Manifest Destiny as landscape painting.",
  "met-0-cole-oxbow":        "Cole painted himself as a tiny figure in the lower right, reminding us that the artist—like nature—is both part of and apart from the sublime.",
  "met-0-canaletto-piazza":  "Canaletto's veduta were sold as souvenirs to Grand Tour travelers; his Venice is real and theatrical simultaneously.",
  "met-0-hals-portrait":     "Hals captured his sitter's psychological vitality with brushwork so loose and alive that it anticipates Manet by two centuries.",
  "met-0-degas-rehearsal":   "A rehearsal, not a performance—Degas preferred the unglamorous preparation, the waiting, the disciplined repetition that produced the illusion of effortless grace.",
  "met-0-gauguin-tahitian-women": "Gauguin's Tahitian women occupy the picture plane with quiet authority, indifferent to the colonial gaze that funded the painting.",
  "met-0-monet-wisteria":    "Monet painted wisteria nearly blind, working at close range—the blooms dissolve into pure color fields that anticipate Abstract Expressionism.",
  "met-0-lautrec-circus":    "Lautrec cropped the circus ring radically, placing us inside the action—an angle no academic painter would dare.",
  "met-0-homer-northeaster":  "Homer painted this Prout's Neck scene multiple times, returning to the Atlantic's raw power as if it held an answer he couldn't yet articulate.",
};

export const STROKE_DESCRIPTIONS: Record<string, string> = {
  "met-436529":              "Short, broken comma-strokes laid side by side — Monet and Renoir were learning to let color mix in the eye rather than on the palette.",
  "met-437980":              "Broad, sweeping arcs applied with wide brushes; at this scale individual strokes dissolve into shimmering atmosphere rather than form.",
  "met-436922":              "Flat, nearly even passages of paint borrowed from Japanese woodblock prints — Monet suppressed modelling to make the scene read as pure color.",
  "met-437984":              "Vigorous, spiraling strokes follow the contours of each form — sky, cypress, and hills are all woven from the same restless rhythm.",
  "met-436528":              "Thick impasto applied in directional dabs that map onto petals and leaves, giving the surface a physical weight the color alone could not achieve.",
  "met-436532":              "Small Pointillist dots of complementary color — Van Gogh was experimenting with Seurat's method, placing pure hues next to each other for optical vibration.",
  "met-436535":              "Bold, confident strokes applied wet-into-wet; the oleander blossoms are built from single loaded brushmarks rather than careful blended shading.",
  "met-436928":              "Short diagonal hatching strokes define the dancers' tutus with almost no blending — Degas wanted the sensation of light catching fabric, not the fabric itself.",
  "met-437654":              "Long, fluid strokes in the background contrast with the precise rendering of the sitter's face, showing Renoir's Impressionist looseness outside the focal point.",
  "met-436005":              "Smooth, finished brushwork that satisfied the Salon — Renoir suppressed his Impressionist instinct here to produce the even surface academic juries rewarded.",
  "met-437394":              "Rembrandt's glazing technique: dozens of thin transparent layers built up over weeks, the final surface lit from within rather than painted on top.",
  "met-29150":              "El Greco's elongated strokes twist with a flickering energy that turns paint into pure spiritual light rather than observed fact.",
  "met-435882":              "Horizontal and vertical strokes of similar weight that deliberately flatten and shift perspective — the foundation of every Cubist painting to come.",
  "met-437539":              "Lautrec used the rough grain of cardboard as part of his brushwork, letting the surface texture break up his strokes into a lithographic dot pattern.",
  "met-421165":              "Broad decorative passages of color with minimal modelling, influenced by Polynesian tapa cloth patterns — Gauguin was moving toward flat symbolic color.",
  "met-61333":              "Heavy, almost sculptural impasto applied with a palette knife as much as a brush — Cézanne was building form through color weight, not line.",
  "met-45434":              "Woodblock printing, not painting: Hokusai's contour lines are cut into wood and printed in registration, the 'strokes' are carved grooves filled with ink.",
  "met-0-vermeer-water-pitcher": "Invisible layered glazes over a detailed underpainting — Vermeer's surface shows almost no individual brushmarks, just accumulated light.",
  "met-0-vermeer-lute":      "Ultra-fine stippling in the lit areas combined with smooth fluid passages in shadow — Vermeer used different brushes for each zone of luminosity.",
  "met-0-vermeer-asleep":    "Loose, fluid strokes in the background tablecloth contrast with the tightly rendered face — an early work where Vermeer was still developing his characteristic stillness.",
  "met-0-sargent-madame-x":  "Rapid, confident strokes applied in a single sitting — Sargent's virtuoso technique built the entire figure from wide sweeping marks that look effortless but hide enormous skill.",
  "met-0-velazquez-pareja":  "Long, tapering strokes that follow the weave of the canvas; Velázquez left individual brushmarks visible at a distance, presaging Manet by two centuries.",
  "met-0-homer-gulf-stream":  "Homer's watercolor-influenced oil technique: thin, translucent washes of blue-green laid over a chalky underpainting to make the sea glow from below.",
  "met-0-homer-snap-whip":   "Quick, calligraphic strokes that capture movement rather than anatomy — Homer painted the action itself, not the boys performing it.",
  "met-0-leutze-washington":  "Academic, fully blended passages designed to look finished rather than painted — Leutze wanted heroic drama, not visible process.",
  "met-0-cassatt-sewing":    "Broken Impressionist strokes in the background with a tighter touch on the figures — Cassatt followed Degas in giving interiors the same vigorous surface as outdoor scenes.",
  "met-0-fragonard-reading":  "Rococo feathered strokes that give the dress and cushion an airy insubstantiality — paint thick enough to catch the light, thin enough to seem like breath.",
  "met-0-monet-haystacks":   "Parallel horizontal strokes in the sky and earth contrasted with textured impasto on the haystack itself — the subject is paint responding to light.",
  "met-0-van-gogh-olive":    "Short, swirling strokes follow the twist of each branch — Van Gogh mapped observed motion onto the surface of the canvas like a seismograph.",
  "met-0-hiroshige-sudden-shower": "Woodblock printing: the rain is thin parallel lines cut into a separate block and overprinted in black — a technique Van Gogh tried to replicate in oil.",
  "met-0-hiroshige-plum":    "Bold flat color fields separated by ink outlines — no modelling or shadow, just the silhouette of each element acting as pure shape.",
  "met-0-bierstadt-rocky":   "Smooth blended passages in the dramatic sky with tighter, more textured work in the foreground rocks — a Hudson River technique for making distance feel infinite.",
  "met-0-cole-oxbow":        "Layered glazes over a toned ground, with visible impasto only in the sunlit passages — Cole used Old Master technique to paint New World wilderness.",
  "met-0-canaletto-piazza":  "Thin, even paint over a precise architectural underdrawing — Canaletto used a camera obscura to project the scene, then painted almost like a printer filling in plates.",
  "met-0-hals-portrait":     "Slashing, rapid strokes applied wet-into-wet in a single session — Hals refused to rework passages, so the brushmarks preserve exactly the speed and pressure of his hand.",
  "met-0-degas-rehearsal":   "Short hatching strokes in pastel over a monotype base — Degas built up his surfaces through layered dry media rather than the liquid brushwork of his Impressionist peers.",
  "met-0-gauguin-tahitian-women": "Large flat planes of saturated color with no blending — Gauguin wanted the picture to read as symbolic color fields, not as modelled flesh.",
  "met-0-monet-wisteria":    "Working nearly blind, Monet applied paint in broad arcs guided by touch as much as sight — the result is more tactile than visual, pure color without contour.",
  "met-0-lautrec-circus":    "Rapid calligraphic strokes that summarize a pose in a few marks — Lautrec could capture a performer's gesture in the time it took to make it.",
  "met-0-homer-northeaster":  "Homer scraped wet paint with a palette knife to create the foam's texture, then painted transparent washes over it — the sea is built as much by removing paint as applying it.",
};

export const PAINTING_DIMENSIONS: Record<string, string> = {
  "met-436529":  "29½ × 39⅜ in",
  "met-437980":  "78¾ × 167⅜ in",
  "met-436922":  "38⅝ × 51¼ in",
  "met-437984":  "28⅞ × 36¾ in",
  "met-436528":  "29 × 36⅛ in",
  "met-436532":  "16⅛ × 12⅝ in",
  "met-436535":  "23¾ × 28⅞ in",
  "met-436928":  "18⅞ × 24⅝ in",
  "met-437654":  "36¼ × 28¾ in",
  "met-436005":  "60½ × 74¾ in",
  "met-437394":  "56½ × 53¾ in",
  "met-29150":   "47¾ × 42¾ in",
  "met-435882":  "21¾ × 29⅛ in",
  "met-437539":  "33⅛ × 26⅜ in",
  "met-421165":  "44½ × 34½ in",
  "met-61333":   "18⅛ × 22⅜ in",
  "met-45434":   "10⅛ × 14⅞ in",
  "met-0-vermeer-water-pitcher": "18 × 16 in",
  "met-0-sargent-madame-x":     "82⅛ × 43¼ in",
  "met-0-velazquez-pareja":      "32 × 27½ in",
  "met-0-leutze-washington":     "149 × 255 in",
  "met-0-homer-gulf-stream":     "28⅛ × 49⅛ in",
};
